#!/usr/bin/env bash
set -e

docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.dev.yml up -d server

CONTAINER=$(docker compose ps | grep server | awk '{print $1}')
docker attach $CONTAINER
